service: sls-template

plugins:

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: ${file(config/config.${self:provider.stage}.json):REGION, 'us-west-2'}
  stage: ${opt:stage, 'local'}
  environment:
    SERVICE_NAME: ${self:service}
    STAGE: ${self:provider.stage}
    REGION: ${self:provider.region}

functions:
  hello:
    handler: src/hello.handler
    events:
      - http:
          path: /
          method: GET

resources:
  # Resource Name
  # - ${file(resources/resourceName.yml)}

custom:
